#Enter chip type en type of board
esp8266:
  board: d1_mini

# Enable Home Assistant API
# Set encryption key
api:
  encryption:
    key: !secret api_key
# Set an ota password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Default is DHCP, uncomment block below for manual config
#  manual_ip:
    # Set this to the IP of the ESP
#    static_ip: xxx.xxx.xxx.xxx
#    gateway: xxx.xxx.xxx.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
#    subnet: 255.255.255.0

# Enable fallback hotspot (captive portal) in case wifi connection fails
# Set hotspot password
  ap:
    ssid: "Esp-LG Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:
