#Enter chip type en type of board
esp32:
  board: esp32dev
  framework:
    type: arduino
# Enable Home Assistant API
# Set encryption key
api:
  encryption:
    key: ""
# Set an ota password
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
# Default is DHCP, uncomment block below for manual config
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.xx.xx
    gateway: 192.168.xx.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable fallback hotspot (captive portal) in case wifi connection fails
# Set hotspot password
  ap:
    ssid: "Esp-LGSIM Fallback Hotspot"
    password: ""

captive_portal:
