#Enter chip type en type of board
esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
# Enable Home Assistant API
# Set encryption key
api:
  encryption:
    key: "gkHIIHxXh5y0IwuaTPOotCoAp5Bk2p3gXuha8GCaKWc="
# Set an ota password
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
# Default is DHCP, uncomment block below for manual config
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.132
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.254.0

# Enable fallback hotspot (captive portal) in case wifi connection fails
# Set hotspot password
  ap:
    ssid: "Esp-LGSIM Fallback Hotspot"
    password: !secret ap_password

captive_portal:
