# Your Wi-Fi SSID
wifi_ssid: ""
# Your Sim Wi-Fi SSID
sim_wifi_ssid: ""
#Your Wi-Fi password
wifi_password: ""
#Your sim Wi-Fi password
sim_wifi_password: ""
ota_password: "change me to random password"
sim_ota_password: "change me to rondom password"
#see https://esphome.io/components/api.html
api_key: "change me to api key"
sim_api_key: "change me to api key"
hotspot_password: "change me to random password"
sim_hotspot_password: "change me to random password"
