substitutions:
  device_name: esp-lg-simulator

esphome:
  name: "${device_name}"
  includes:
    - lg_heatpump_functions.h
  on_boot:
    priority: 200
    then:
      lambda: !lambda |-
          //instant on (in case of controller restart during run)
          id(relay_backup_heat).turn_off();
          if(id(thermostat_signal).state) {
            id(relay_pump).turn_on();
            id(relay_heat).turn_on();
          } else {
            id(relay_pump).turn_off();
            id(relay_heat).turn_off();
          }
          id(controller_state).publish_state("Initialiseren");
          
packages:
  config_values: !include config/config_simulator.yaml
  lg_modbus: !include lg_heatpump_fake_modbus.yaml #include file with simulated modbus sensors
  
# Enable logging. Disable modbus controller debug messages
logger:
  logs:
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    number: WARN

globals:
  - id: update_stooklijn
    type: bool
    restore_value: no
    initial_value: 'true'
  - id: boost_bool
    type: bool
    restore_value: no
    initial_value: 'false'

number:
  - platform: template
    name: "Stooklijn offset Sim"
    id: wp_stooklijn_offset
    min_value: -5
    max_value: 5
    initial_value: 0
    step: 1
    restore_value: yes
    unit_of_measurement: "°C"
    optimistic: true
    icon: mdi:plus-minus-variant
    set_action:
      then:
        lambda: !lambda |-
            id(update_stooklijn) = true;
  - platform: template
    id: stooklijn_curve
    name: "Stooklijn Curve Sim"
    min_value: -6
    max_value: 6
    step: 0.5
    restore_value: yes
    initial_value: -3
    optimistic: true
    icon: mdi:chart-bell-curve-cumulative
    set_action:
      then:
        lambda: !lambda |-
            id(update_stooklijn) = true;
  - platform: template
    id: stooklijn_min_oat
    name: "Stooklijn Minimum Buitentemperatuur Sim"
    min_value: -25
    max_value: 0
    step: 1
    restore_value: yes
    initial_value: -10
    unit_of_measurement: "°C"
    optimistic: true
    icon: mdi:download-circle-outline
    set_action:
      then:
        lambda: !lambda |-
            id(update_stooklijn) = true;
  - platform: template
    id: stooklijn_max_wtemp
    name: "Stooklijn Maximum Watertemperatuur Sim"
    min_value: 20
    max_value: 60
    step: 1
    restore_value: yes
    initial_value: 46
    unit_of_measurement: "°C"
    optimistic: true
    icon: mdi:waves-arrow-right
    set_action:
      then:
        lambda: !lambda |-
            id(update_stooklijn) = true;
  - platform: template
    id: stooklijn_min_wtemp
    name: "Stooklijn Minimum Watertemperatuur Sim"
    min_value: 20
    max_value: 40
    step: 1
    restore_value: yes
    initial_value: 28
    unit_of_measurement: "°C"
    optimistic: true
    icon: mdi:waves-arrow-left
    set_action:
      then:
        lambda: !lambda |-
            id(update_stooklijn) = true;
  - platform: template
    id: minimum_run_time
    name: "Minimale run tijd Sim"
    min_value: 0
    max_value: 60
    step: 1
    restore_value: yes
    initial_value: 30
    unit_of_measurement: "min"
    optimistic: true
    icon: mdi:timer-sync-outline
  - platform: template
    id: external_pump_runover
    name: "External pump overrun Sim"
    min_value: 0
    max_value: 60
    step: 1
    restore_value: yes
    initial_value: 10
    unit_of_measurement: "min"
    optimistic: true
    icon: mdi:timer-cog-outline
  - platform: template
    id: oat_silent_always_off
    name: "Buitentemperatuur silent always off Sim"
    min_value: -20
    max_value: 10
    step: 1
    restore_value: yes
    initial_value: 2
    unit_of_measurement: "°C"
    optimistic: true
    icon: mdi:volume-plus
  - platform: template
    id: oat_silent_always_on
    name: "Buitentemperatuur silent always on Sim"
    min_value: -20
    max_value: 20
    step: 1
    restore_value: yes
    initial_value: 6
    unit_of_measurement: "°C"
    optimistic: true
    icon: mdi:volume-off
  - platform: template
    id: thermostat_off_delay
    name: "Thermostat off delay Sim"
    min_value: 0
    max_value: 10
    step: 1
    restore_value: yes
    initial_value: 1
    unit_of_measurement: "min"
    optimistic: true
    icon: mdi:timer-off-outline
  - platform: template
    id: thermostat_on_delay
    name: "Thermostat on delay Sim"
    min_value: 0
    max_value: 10
    step: 1
    restore_value: yes
    initial_value: 0
    unit_of_measurement: "min"
    optimistic: true
    icon: mdi:timer
  - platform: template
    id: boost_time
    name: "Boost duration Sim"
    min_value: 0
    max_value: 180
    step: 1
    restore_value: yes
    initial_value: 60
    unit_of_measurement: "min"
    optimistic: true
    icon: mdi:timer-plus-outline
  - platform: template
    id: backup_heater_active_temp
    name: "Buitentemperatuur backup heater active Sim"
    min_value: -30
    max_value: 20
    step: 1
    restore_value: yes
    initial_value: 2
    optimistic: true
    icon: mdi:gas-burner

switch:
  - platform: template
    name: "Termostat On Sim"
    id: thermostat_signal
    optimistic: true
  - platform: template
    name: "External pump relay Sim"
    id: "relay_pump"
    optimistic: true
  - platform: template
    name: "Heat relay  Sim"
    id: "relay_heat"
    optimistic: true
  - platform: template
    name: "Backup_heat relay Sim"
    id: "relay_backup_heat"
    optimistic: true
    icon: mdi:gas-burner
  - platform: restart
    name: "ESP WP Control Restart  Sim"
  - platform: template
    name: "Temperature Boost Sim"
    id: boost_switch
    lambda: |-
        return id(boost_bool);
    turn_on_action:
      - globals.set:
          id: boost_bool
          value: 'true'
    turn_off_action:
      - globals.set:
          id: boost_bool
          value: 'false'
    icon: mdi:thermometer-plus

interval:
  - interval: 10s
    id: state_machine
    then: !include { file: lg_heatpump_state_machine.yaml }
  - interval: 20s
    id: simulation
    then: !include { file: lg_heatpump_simulation_script.yaml }

binary_sensor:
  - platform: template
    name: "Boost mode active  Sim"
    id: boost_active
    lambda: |-
        return id(boost_bool);
    icon: mdi:thermometer-plus

sensor:
  - platform: template
    name: "Stooklijn Watertemp Target Sim"
    id: watertemp_target
    unit_of_measurement: "°C"
    update_interval: never
    icon: mdi:home-thermometer-outline
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 120s
    accuracy_decimals: 0
  - platform: uptime
    name: "${device_name} Uptime"
    unit_of_measurement: days
    update_interval: 3600s
    accuracy_decimals: 1
    filters:
      - multiply: 0.000011574
  - platform: template
    name: "Delta T Sim"
    id: wp_delta_t
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
        return (float)((id(water_temp_aanvoer).state)-(id(water_temp_retour).state)); 
    update_interval: 30s
    icon: mdi:delta
  - platform: template
    name: "Derivative Sim"
    id: derivative_value
    accuracy_decimals: 1
    unit_of_measurement: "°C/h" 
    update_interval: never  
    icon: mdi:sigma
  #very innacurate, use only for global reference
  - platform: template
    name: "COP guess Sim"
    id: cop_guess
    lambda: |-
      if(id(current_flow_rate).state < 6 || id(wp_delta_t).state <= 0) return 0;
      if(!id(compressor_running).state || id(wp_sensed_power).state < 300) return 0;
      if(id(wp_delta_t).state < 0) return 0;
      return ((id(current_flow_rate).state/60)*(id(wp_delta_t).state*4184))/id(wp_sensed_power).state;
    accuracy_decimals: 1
    unit_of_measurement: "COP"
    update_interval: 60 sec
    icon: mdi:approximately-equal
  - platform: template
    name: "Average cop Sim"
    id: average_cop_sensor
    accuracy_decimals: 1
    unit_of_measurement: "COP" 
    update_interval: never  
    icon: mdi:sigma
# Sensors for ESP version and WIFI information
text_sensor:
  - platform: version
    name: "${device_name} ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "${device_name} ip"
      icon: mdi:ip-network
    ssid:
      name: "${device_name} ssid"
      icon: mdi:wifi-marker
  - platform: template
    name: "Controller state Sim"
    id: controller_state
    update_interval: never
    icon: mdi:state-machine
  - platform: template
    name: "Controller info Sim"
    id: controller_info
    update_interval: never
    icon: mdi:memory