dallas:
  - pin: 32

sensor:
  - platform: dallas
    address: 0x4a0122113a9bd528
    name: "WPB Bottom Temperature"
  - platform: dallas
    address: 0xb9012211506ebf28
    name: "WPB Top Temperature"
  - platform: dallas
    address: 0xe101221102a46b28
    name: "Buffer Top Temperature"
  - platform: dallas
    address: 0xd7000801c04e3210
    name: "Buffer Bottom Temperature"
  - platform: dallas
    address: 0xd10122112fc5ee28
    name: "Inlet Junction Temperature"
  - platform: dallas
    address: 0x2403069794065c28
    name: "Outlet Junction Temperature"
  - platform: dallas
    address: 0xbb03059497154628
    name: "SWW Outlet Temperature"
