dallas:
  - pin: 32

sensor:
  - platform: dallas
    address: 0x4a0122113a9bd528
    name: "WPB Bottom Temperature"
  - platform: dallas
    address: 0xb9012211506ebf28
    name: "WPB Top Temperature"
  - platform: dallas
    address: 0xe101221102a46b28
    name: "Buffer Top Temperature"
  - platform: dallas
    address: 0xd7000801c04e3210
    name: "Buffer Bottom Temperature"
  - platform: dallas
    address: 0xd10122112fc5ee28
    name: "CV Supply Junction Temperature"
  - platform: dallas
    address: 0x2403069794065c28
    name: "CV Return Junction Temperature"
  - platform: dallas
    address: 0xbb03059497154628
    name: "SWW Supply Temperature"
  - platform: dallas
    address: 0x38030794971a4a28
    name: "CV Supply Temperature"
  - platform: dallas
    address: 0x4503059497174a28
    name: "CV Return Temperature"

