one_wire:
  - platform: gpio
    pin: GPIO15

sensor:
  - platform: dallas_temp
    update_interval: 60s
    address: 0x0b3c01f095fda128
    name: "HP Taaanvoer"
    id: Taanvoer
    device_class: "temperature"
    unit_of_measurement: "째C"
    state_class: "measurement"
    filters:
      - offset: 0.1
    icon: mdi:radiator
  - platform: dallas_temp
    update_interval: 60s
    address: 0x533ce6f649409b28
    name: "HP Tretour"
    id: Tretour
    device_class: "temperature"
    unit_of_measurement: "째C"
    state_class: "measurement"    
    filters:
      - offset: 0.1
    icon: mdi:radiator-disabled
  - platform: dallas_temp
    update_interval: 60s
    address: 0x633c01f0953ae328
    name: "Kruipruimte Temperature"
    filters:
      - offset: 0.1
    icon: mdi:alpha-t-circle-outline
  - platform: dallas_temp
    update_interval: 60s
    address: 0x203cd1f649dd3a28
    name: "HP CV Taaanvoer"
    id: CVTaanvoer
    device_class: "temperature"
    unit_of_measurement: "째C"
    state_class: "measurement"    
    filters:
      - offset: 0.1
    icon: mdi:radiator
  - platform: dallas_temp
    update_interval: 60s
    address: 0xd83c8bf649c03128
    name: "HP CV Tretour"
    id: CVTretour
    device_class: "temperature"
    unit_of_measurement: "째C"
    state_class: "measurement"    
    filters:
      - offset: 0.1
    icon: mdi:radiator-disabled 