modbus:
  id: modbus_lg
  uart_id: uart_modbus
  flow_control_pin: GPIO5
  send_wait_time: 200ms
  
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  id: uart_modbus
  parity: none
  data_bits: 8
  stop_bits: 1

modbus_controller:
  - id: lg
    address: 0x1 # the Modbus device addr
    modbus_id: modbus_lg
    update_interval: 30s
    setup_priority: -10

switch:
  - platform: modbus_controller
    name: "Silent Mode"
    modbus_controller_id: lg
    id: silent_mode_switch
    register_type: coil
    address: 2
    icon: mdi:volume-off
  - platform: modbus_controller
    name: "SWW On/Off"
    modbus_controller_id: lg
    id: sww_on_off
    register_type: coil
    address: 1
    icon: mdi:shower-head
  
binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pump Running"
    id: pump_running
    register_type: discrete_input
    skip_updates: 1
    address: 1
    icon: mdi:pump
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Running"
    id: compressor_running
    register_type: discrete_input
    skip_updates: 1
    address: 3
    icon: mdi:car-turbocharger
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Defrosting"
    id: defrosting
    register_type: discrete_input
    skip_updates: 1
    address: 4
    icon: mdi:snowflake-melt
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "SWW Heating"
    id: sww_heating
    register_type: discrete_input
    skip_updates: 1
    address: 5
    icon: mdi:shower-head
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Silent Mode"
    id: silent_mode_state
    register_type: discrete_input
    skip_updates: 1
    address: 7
    icon: mdi:volume-off

sensor:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Bedrijfsmodus"
    id: bedrijfsmodus
    register_type: read
    address: 1
    #skip_updates: 12
    value_type: U_WORD
    icon: mdi:information-outline
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Water retour"
    id: water_temp_retour
    register_type: read
    address: 2
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-chevron-down
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Water aanvoer"
    id: water_temp_aanvoer
    register_type: read
    address: 3
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-chevron-up
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "SWW Temperatuur"
    id: sww_temp
    register_type: read
    address: 5
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-water
  - platform: template
    name: "Rounded SWW Temperature"
    id: rounded_sww_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return (float)(floor((id(sww_temp).state*2)+0.5)/2);
    update_interval: 30s
    icon: mdi:thermometer-water
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Garagetemperatuur"
    id: binnen_temp
    register_type: read
    address: 7
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:garage-open-variant
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Flow Rate"
    id: current_flow_rate
    register_type: read
    address: 8
    unit_of_measurement: "L/m"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    lambda: |-
      if(x > 5) return x;
      else return 0.0;
    icon: mdi:waves-arrow-right
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Buitentemperatuur"
    id: buiten_temp
    register_type: read
    address: 12
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    icon: mdi:weather-cloudy
    filters:
      - multiply: 0.1
      - sliding_window_moving_average:
          window_size: 60
          send_every: 30
  - platform: template
    name: "Filtered OAT"
    id: filtered_oat
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      static float prev_oat = -100.0;
      float new_oat = floor(id(buiten_temp).state);
      if(new_oat - prev_oat > 0.5) {
        fsm.update_stooklijn();
        prev_oat = new_oat;
      }
      return new_oat;
    update_interval: 60s
    filters:
      - or:
        - throttle: 90min
        - delta: 2.0
    icon: mdi:weather-cloudy
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pipe in Temp"
    id: temp16
    register_type: read
    address: 16
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pipe Out Temp"
    id: temp17
    register_type: read
    address: 17
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Suction Temp"
    id: temp18
    register_type: read
    address: 18
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Temp"
    id: compressor_temp
    register_type: read
    address: 19
    unit_of_measurement: "°C"
    value_type: S_WORD
    filters:
      - multiply: 0.1
    accuracy_decimals: 1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Condensor Temp"
    id: condensor_temp
    register_type: read
    address: 20
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:hvac
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "High Press"
    id: high_press
    register_type: read
    address: 22
    value_type: U_WORD
    accuracy_decimals: 0
    unit_of_measurement: "mbar"
    icon: mdi:meter-electric-outline
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Low Press"
    id: low_press
    register_type: read
    address: 23
    value_type: U_WORD
    accuracy_decimals: 0
    unit_of_measurement: "mbar"
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Hz"
    id: compressor_rpm
    register_type: read
    address: 24
    unit_of_measurement: "Hz"
    value_type: U_WORD
    accuracy_decimals: 0
    icon: mdi:car-turbocharger
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Doeltemperatuur"
    id: doel_temp
    register_type: holding
    address: 2
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    skip_updates: 3
    filters:
      - multiply: 0.1
    icon: mdi:home-thermometer-outline
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "SWW Doeltemperatuur"
    id: sww_target
    register_type: holding
    address: 8
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    skip_updates: 3
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-water
  - platform: template
    name: "Delta T"
    id: wp_delta_t
    unit_of_measurement: "K"
    accuracy_decimals: 1
    lambda: |-
      return (float)(id(corrected_water_temp_aanvoer).state-id(corrected_water_temp_retour).state); 
    update_interval: 30s
    icon: mdi:delta
  - platform: template
    name: "Corrected retour"
    id: corrected_water_temp_retour
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return (float)(id(water_temp_retour).state-0.4); 
    update_interval: 30s
    icon: mdi:thermometer-chevron-down
  - platform: template
    name: "Rounded Corrected retour"
    id: rounded_corrected_water_temp_retour
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return (float)(floor((id(corrected_water_temp_retour).state*2)+0.5)/2);
    update_interval: 30s
    icon: mdi:thermometer-chevron-down
  - platform: template
    name: "Corrected aanvoer"
    id: corrected_water_temp_aanvoer
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return (float)(id(water_temp_aanvoer).state+0.5); 
    update_interval: 30s
    icon: mdi:thermometer-chevron-up
  - platform: template
    name: "Rounded Corrected aanvoer"
    id: rounded_corrected_water_temp_aanvoer
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      return (float)(floor((id(corrected_water_temp_aanvoer).state*2)+0.5)/2);
    update_interval: 30s
    icon: mdi:thermometer-chevron-up

number:
  - platform: modbus_controller
    modbus_controller_id: lg
    id: water_temp_target_output
    register_type: holding
    address: 2
    value_type: U_WORD
    step: 0.1
    multiply: 10