binary_sensor:
# Provide thermostat signal to state machine code from climate thermostat (LG RMC Room temperature)
  - platform: template
    name: "HP Thermostat Signal (flow status)"
    id: thermostat_signal
    lambda: |-
      return id(heater).state;
    icon: mdi:thermostat 

# Switch for thermostat
switch:
  - platform: template
    name: "virtual switch thermostat"
    id: heater
    optimistic: true
 
# ESPhome thermostat, RMC room temperature ad sensor swicthes "heater"  
climate:
  - platform: thermostat
    name: "HP Thermostat Signal"
    sensor: binnen_temp
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    on_boot_restore_from: memory
    heat_deadband: 0.4
    heat_overrun: 0.4
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
    default_preset: Woonkamer
    preset:
      - name: Woonkamer
        default_target_temperature_low: 20
        mode: heat    