binary_sensor:
  - platform: gpio # Thermostat input signal is connected to this input pin
    pin:
      number: GPIO27
      mode:
        input: true
        pullup: false
    name: "WP Nest Signal"
    id: thermostat_signal
    filters:
      - delayed_on: 500ms # Debounce
    icon: mdi:thermostat
